# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9e6275a105844ab1472f119437c9fc54f770a0b4048009213b23bdd71ac0083bd9b736e280676aea65869d67d96828e58e22ae70ee7f3dca5e288b12027f270

test:
  secret_key_base: ac8a2920d635c75c887ab1cfda446f0f79f0ddf908d008a806e12825381c3ce07e8cba620df9ead7a65d716e0f39f0f66154f0e80fba8a10e8d4801a7ed2a28c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
